### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ewinnington** [ewinnington/wfRunnerCore#1]
Host in a asp.net core rest webapi: 

- [ ] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2
- [ ] Add an in memory DB, for example SQLite to host activity dll, workflows and logs
- [ ] Add web view & signal R

Add demo workflows and listener services:

- [x] Add a Workflow and Workflow activities demonstrating FTP

- [x] FTP listener service

- [x] Add a Workflow and Workflow activities demonstrating email

- [x] mail listener service

**Comment by ewinnington** [comment]
Add a Workflow and Workflow activities demonstrating FTP
Add a Workflow and Workflow activities demonstrating email 

Add ftp and mail listener services so that the repo can be run locally.

**Comment by ewinnington** [comment]
no longer relevant
